// THIS FILE WAS AUTOMATICALLY GENERATED

/* ------------------------------------------------------------------------ */
/* flag */

static KMETHOD _String_isASCII(CTX, ksfp_t *sfp _RIX)
{
	RETURNb_(String_isASCII((kString*)sfp[0].o));
}

static KMETHOD _String_isPooled(CTX, ksfp_t *sfp _RIX)
{
	RETURNb_(String_isPooled((kString*)sfp[0].o));
}

static KMETHOD _OutputStream_isAutoFlush(CTX, ksfp_t *sfp _RIX)
{
	RETURNb_(OutputStream_isAutoFlush((kOutputStream*)sfp[0].o));
}

static KMETHOD _OutputStream_setAutoFlush(CTX, ksfp_t *sfp _RIX)
{
	OutputStream_setAutoFlush((kOutputStream*)sfp[0].o, sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

static KMETHOD _Context_isDebug(CTX, ksfp_t *sfp _RIX)
{
	RETURNb_(CTX_isDebug(((sfp[0].cx)->ctx)));
}

static KMETHOD _Context_setDebug(CTX, ksfp_t *sfp _RIX)
{
	CTX_setDebug(((sfp[0].cx)->ctx), sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

/* ------------------------------------------------------------------------ */
/* data */

static const char * StringData0[] = {
	"", /* TS_EMPTY */
	"\t", /* TS_TAB */
	"1", /* TS_ONE */
	""K_OSLINEFEED"", /* TS_EOL */
	"BEGIN", /* TS_BEGIN */
	"END", /* TS_END */
	"main", /* TS_main */
	""K_ENCODING"", /* TS_ENCODING */
	"/dev/null", /* TS_DEVNULL */
	"/dev/stdin", /* TS_DEVSTDIN */
	"/dev/stderr", /* TS_DEVSTDERR */
	"/dev/stdout", /* TS_DEVSTDOUT */
	"@label", /* TS_ATlabel */
	NULL
};

static kloaddata_t StructData0[] = {
	DATA_STRUCT0, CLASS_Tvoid, _DATA(&TvoidDef), CFLAG_Tvoid,
	DATA_STRUCT0, CLASS_Tvar, _DATA(&TvarDef), CFLAG_Tvar,
	DATA_STRUCT0, CLASS_Object, _DATA(&ObjectDef), CFLAG_Object,
	DATA_STRUCT0, CLASS_Boolean, _DATA(&BooleanDef), CFLAG_Boolean,
	DATA_STRUCT0, CLASS_Number, _DATA(&NumberDef), CFLAG_Number,
	DATA_STRUCT0, CLASS_Int, _DATA(&IntDef), CFLAG_Int,
	DATA_STRUCT0, CLASS_Float, _DATA(&FloatDef), CFLAG_Float,
	DATA_STRUCT0, CLASS_Date, _DATA(&DateDef), CFLAG_Date,
	DATA_STRUCT0, CLASS_String, _DATA(&StringDef), CFLAG_String,
	DATA_STRUCT0, CLASS_Bytes, _DATA(&BytesDef), CFLAG_Bytes,
	DATA_STRUCT0, CLASS_Pointer, _DATA(&PointerDef), CFLAG_Pointer,
	DATA_STRUCT0, CLASS_Iterator, _DATA(&IteratorDef), CFLAG_Iterator,
	DATA_STRUCT0, CLASS_Tuple, _DATA(&TupleDef), CFLAG_Tuple,
	DATA_STRUCT0, CLASS_Range, _DATA(&RangeDef), CFLAG_Range,
	DATA_STRUCT0, CLASS_Array, _DATA(&ArrayDef), CFLAG_Array,
	DATA_STRUCT0, CLASS_Map, _DATA(&MapDef), CFLAG_Map,
	DATA_STRUCT0, CLASS_Class, _DATA(&ClassDef), CFLAG_Class,
	DATA_STRUCT0, CLASS_Param, _DATA(&ParamDef), CFLAG_Param,
	DATA_STRUCT0, CLASS_Method, _DATA(&MethodDef), CFLAG_Method,
	DATA_STRUCT0, CLASS_TypeMap, _DATA(&TypeMapDef), CFLAG_TypeMap,
	DATA_STRUCT0, CLASS_Func, _DATA(&FuncDef), CFLAG_Func,
	DATA_STRUCT0, CLASS_Thunk, _DATA(&ThunkDef), CFLAG_Thunk,
	DATA_STRUCT0, CLASS_Exception, _DATA(&ExceptionDef), CFLAG_Exception,
	DATA_STRUCT0, CLASS_ExceptionHandler, _DATA(&ExceptionHandlerDef), CFLAG_ExceptionHandler,
	DATA_STRUCT0, CLASS_Regex, _DATA(&RegexDef), CFLAG_Regex,
	DATA_STRUCT0, CLASS_Converter, _DATA(&ConverterDef), CFLAG_Converter,
	DATA_STRUCT0, CLASS_StringEncoder, _DATA(&StringEncoderDef), CFLAG_StringEncoder,
	DATA_STRUCT0, CLASS_StringDecoder, _DATA(&StringDecoderDef), CFLAG_StringDecoder,
	DATA_STRUCT0, CLASS_StringConverter, _DATA(&StringConverterDef), CFLAG_StringConverter,
	DATA_STRUCT0, CLASS_Semantics, _DATA(&SemanticsDef), CFLAG_Semantics,
	DATA_STRUCT0, CLASS_Path, _DATA(&PathDef), CFLAG_Path,
	DATA_STRUCT0, CLASS_InputStream, _DATA(&InputStreamDef), CFLAG_InputStream,
	DATA_STRUCT0, CLASS_OutputStream, _DATA(&OutputStreamDef), CFLAG_OutputStream,
	DATA_STRUCT0, CLASS_View, _DATA(&ViewDef), CFLAG_View,
	DATA_STRUCT0, CLASS_KonohaSpace, _DATA(&KonohaSpaceDef), CFLAG_KonohaSpace,
	DATA_STRUCT0, CLASS_Script, _DATA(&ScriptDef), CFLAG_Script,
	DATA_STRUCT0, CLASS_System, _DATA(&SystemDef), CFLAG_System,
	DATA_STRUCT0, CLASS_Context, _DATA(&ContextDef), CFLAG_Context,
	DATA_STRUCT0, CLASS_Assurance, _DATA(&AssuranceDef), CFLAG_Assurance,
	DATA_STRUCT0, CLASS_Token, _DATA(&TokenDef), CFLAG_Token,
	DATA_STRUCT0, CLASS_Sugar, _DATA(&SugarDef), CFLAG_Sugar,
	DATA_STRUCT0, CLASS_Expr, _DATA(&ExprDef), CFLAG_Expr,
	DATA_STRUCT0, CLASS_Stmt, _DATA(&StmtDef), CFLAG_Stmt,
	DATA_STRUCT0, CLASS_Block, _DATA(&BlockDef), CFLAG_Block,
	DATA_STRUCT0, CLASS_Gamma, _DATA(&GammaDef), CFLAG_Gamma,
	DATA_STRUCT0, CLASS_Lang, _DATA(&LangDef), CFLAG_Lang,
	DATA_STRUCT0, CLASS_Term, _DATA(&TermDef), CFLAG_Term,
	DATA_STRUCT0, CLASS_StmtExpr, _DATA(&StmtExprDef), CFLAG_StmtExpr,
	DATA_STRUCT0, CLASS_GammaBuilder, _DATA(&GammaBuilderDef), CFLAG_GammaBuilder,
	DATA_STRUCT0, CLASS_BasicBlock, _DATA(&BasicBlockDef), CFLAG_BasicBlock,
	DATA_STRUCT0, CLASS_KonohaCode, _DATA(&KonohaCodeDef), CFLAG_KonohaCode,
	DATA_STRUCT0, CLASS_Immutable, _DATA(&ImmutableDef), CFLAG_Immutable,
	DATA_STRUCT0, CLASS_KindOf, _DATA(&KindOfDef), CFLAG_KindOf,
	DATA_STRUCT0, CLASS_Tdynamic, _DATA(&TdynamicDef), CFLAG_Tdynamic,
	0
};

static kloaddata_t ClassData0[] = {
	DATA_CLASS0, CLASS_Tvoid, _DATA("konoha.Tvoid"), CFLAG_Tvoid, CLASS_Tvoid, CLASS_Tvoid, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Tvar, _DATA("konoha.Tvar"), CFLAG_Tvar, CLASS_Tvar, CLASS_Tvoid, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Object, _DATA("konoha.Object"), CFLAG_Object, CLASS_ObjectField, CLASS_Object, 19 + 5 /*0*/,
	DATA_CLASS0, CLASS_Boolean, _DATA("konoha.Boolean"), CFLAG_Boolean, CLASS_Boolean, CLASS_Object, 1 + 4 /*1*/,
	DATA_CLASS0, CLASS_Number, _DATA("konoha.Number"), CFLAG_Number, CLASS_Number, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Int, _DATA("konoha.Int"), CFLAG_Int, CLASS_Int, CLASS_Number, 21 + 10 /*2*/,
	DATA_CLASS0, CLASS_Float, _DATA("konoha.Float"), CFLAG_Float, CLASS_Float, CLASS_Number, 13 + 7 /*2*/,
	DATA_CLASS0, CLASS_Date, _DATA("konoha.Date"), CFLAG_Date, CLASS_Date, CLASS_Object, 2 + 0 /*1*/,
	DATA_CLASS0, CLASS_String, _DATA("konoha.String"), CFLAG_String, CLASS_String, CLASS_Object, 30 + 0 /*5*/,
	DATA_CLASS0, CLASS_Bytes, _DATA("konoha.Bytes"), CFLAG_Bytes, CLASS_Bytes, CLASS_Object, 10 + 0 /*2*/,
	DATA_CLASS0, CLASS_Pointer, _DATA("konoha.Pointer"), CFLAG_Pointer, CLASS_Pointer, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Iterator, _DATA("konoha.Iterator"), CFLAG_Iterator, CLASS_Iterator, CLASS_Object, 3 + 0 /*0*/,
	DATA_CLASS0, CLASS_Tuple, _DATA("konoha.Tuple"), CFLAG_Tuple, CLASS_Tuple, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Range, _DATA("konoha.Range"), CFLAG_Range, CLASS_Range, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Array, _DATA("konoha.Array"), CFLAG_Array, CLASS_Array, CLASS_Object, 28 + 0 /*0*/,
	DATA_CLASS0, CLASS_Map, _DATA("konoha.Map"), CFLAG_Map, CLASS_Map, CLASS_Object, 9 + 0 /*0*/,
	DATA_CLASS0, CLASS_Class, _DATA("konoha.Class"), CFLAG_Class, CLASS_Class, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Param, _DATA("konoha.Param"), CFLAG_Param, CLASS_Param, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Method, _DATA("konoha.Method"), CFLAG_Method, CLASS_Method, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_TypeMap, _DATA("konoha.TypeMap"), CFLAG_TypeMap, CLASS_TypeMap, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Func, _DATA("konoha.Func"), CFLAG_Func, CLASS_Func, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Thunk, _DATA("konoha.Thunk"), CFLAG_Thunk, CLASS_Thunk, CLASS_Object, 3 + 0 /*1*/,
	DATA_CLASS0, CLASS_Exception, _DATA("konoha.Exception"), CFLAG_Exception, CLASS_Exception, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_ExceptionHandler, _DATA("konoha.ExceptionHandler"), CFLAG_ExceptionHandler, CLASS_ExceptionHandler, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Regex, _DATA("konoha.Regex"), CFLAG_Regex, CLASS_Regex, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Converter, _DATA("konoha.Converter"), CFLAG_Converter, CLASS_Converter, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringEncoder, _DATA("konoha.StringEncoder"), CFLAG_StringEncoder, CLASS_StringEncoder, CLASS_Converter, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringDecoder, _DATA("konoha.StringDecoder"), CFLAG_StringDecoder, CLASS_StringDecoder, CLASS_Converter, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringConverter, _DATA("konoha.StringConverter"), CFLAG_StringConverter, CLASS_StringConverter, CLASS_Converter, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Semantics, _DATA("konoha.Semantics"), CFLAG_Semantics, CLASS_Semantics, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Path, _DATA("konoha.Path"), CFLAG_Path, CLASS_Path, CLASS_Object, 2 + 0 /*4*/,
	DATA_CLASS0, CLASS_InputStream, _DATA("konoha.InputStream"), CFLAG_InputStream, CLASS_InputStream, CLASS_Object, 4 + 0 /*1*/,
	DATA_CLASS0, CLASS_OutputStream, _DATA("konoha.OutputStream"), CFLAG_OutputStream, CLASS_OutputStream, CLASS_Object, 9 + 0 /*0*/,
	DATA_CLASS0, CLASS_View, _DATA("konoha.View"), CFLAG_View, CLASS_View, CLASS_Object, 3 + 0 /*0*/,
	DATA_CLASS0, CLASS_KonohaSpace, _DATA("konoha.KonohaSpace"), CFLAG_KonohaSpace, CLASS_KonohaSpace, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Script, _DATA("konoha.Script"), CFLAG_Script, CLASS_Script, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_System, _DATA("konoha.System"), CFLAG_System, CLASS_System, CLASS_Object, 13 + 0 /*0*/,
	DATA_CLASS0, CLASS_Context, _DATA("konoha.Context"), CFLAG_Context, CLASS_Context, CLASS_Object, 4 + 0 /*0*/,
	DATA_CLASS0, CLASS_Assurance, _DATA("konoha.Assurance"), CFLAG_Assurance, CLASS_Assurance, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Token, _DATA("konoha.Token"), CFLAG_Token, CLASS_Token, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Sugar, _DATA("konoha.Sugar"), CFLAG_Sugar, CLASS_Sugar, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Expr, _DATA("konoha.Expr"), CFLAG_Expr, CLASS_Expr, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Stmt, _DATA("konoha.Stmt"), CFLAG_Stmt, CLASS_Stmt, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Block, _DATA("konoha.Block"), CFLAG_Block, CLASS_Block, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Gamma, _DATA("konoha.Gamma"), CFLAG_Gamma, CLASS_Gamma, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Lang, _DATA("konoha.Lang"), CFLAG_Lang, CLASS_Lang, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Term, _DATA("konoha.Term"), CFLAG_Term, CLASS_Term, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_StmtExpr, _DATA("konoha.StmtExpr"), CFLAG_StmtExpr, CLASS_StmtExpr, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_GammaBuilder, _DATA("konoha.GammaBuilder"), CFLAG_GammaBuilder, CLASS_GammaBuilder, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_BasicBlock, _DATA("konoha.BasicBlock"), CFLAG_BasicBlock, CLASS_BasicBlock, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_KonohaCode, _DATA("konoha.KonohaCode"), CFLAG_KonohaCode, CLASS_KonohaCode, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Immutable, _DATA("konoha.Immutable"), CFLAG_Immutable, CLASS_Immutable, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_KindOf, _DATA("konoha.KindOf"), CFLAG_KindOf, CLASS_KindOf, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Tdynamic, _DATA("konoha.Tdynamic"), CFLAG_Tdynamic, CLASS_Tdynamic, CLASS_Object, 1 + 0 /*0*/,
	DATA_GENERICS/*IteratorVar*/, CLASS_Iterator, 1, 0, T_Tvar, FN_,
	DATA_GENERICS/*DataITR*/, CLASS_Iterator, 1, 0, T_Map, FN_,
	DATA_GENERICS/*FuncEach*/, CLASS_Func, 1, 1, T_T1, FN_, T_T1, FN_,
	DATA_GENERICS/*FuncWhere*/, CLASS_Func, 1, 1, T_T1, FN_, TY_Boolean, FN_,
	DATA_GENERICS/*RangeInt*/, CLASS_Range, 1, 0, TY_Int, FN_,
	DATA_GENERICS/*ArrayInt*/, CLASS_Array, 1, 0, TY_Int, FN_,
	DATA_GENERICS/*CmprT1*/, CLASS_Func, 2, 1, T_T1, FN_, T_T1, FN_, TY_Int, FN_,
	DATA_GENERICS/*StringARRAY*/, CLASS_Array, 1, 0, TY_String, FN_,
	DATA_GENERICS/*StringITR*/, CLASS_Iterator, 1, 0, TY_String, FN_,
	DATA_GENERICS/*T1ARRAY*/, CLASS_Array, 1, 0, T_T1, FN_,
	DATA_EXPT, _DATA("Exception"), 0, EVENT_Exception, EVENT_Exception, 
	DATA_EXPT, _DATA("Assertion"), 0, EVENT_Assertion, EVENT_Exception, 
	DATA_EXPT, _DATA("Script"), 0, EVENT_Script, EVENT_Exception, 
	DATA_EXPT, _DATA("StackOverflow"), 0, EVENT_StackOverflow, EVENT_Script, 
	DATA_EXPT, _DATA("Security"), 0, EVENT_Security, EVENT_Exception, 
	0
};

static kloadsymbol_t FieldNameData0[] = {
	{"", FN_},
	{"2", FN_2},
	{"3", FN_3},
	{"4", FN_4},
	{"add", FN_add},
	{"addView", FN_addView},
	{"all", FN_all},
	{"aSCII", FN_aSCII},
	{"auto", FN_auto},
	{"autoFlush", FN_autoFlush},
	{"base", FN_base},
	{"bits", FN_bits},
	{"buf", FN_buf},
	{"c", FN_c},
	{"cast", FN_cast},
	{"class", FN_class},
	{"clear", FN_clear},
	{"close", FN_close},
	{"cmd", FN_cmd},
	{"cmr", FN_cmr},
	{"concat", FN_concat},
	{"convert", FN_convert},
	{"d", FN_d},
	{"data", FN_data},
	{"day", FN_day},
	{"debug", FN_debug},
	{"decode", FN_decode},
	{"defined", FN_defined},
	{"delegate", FN_delegate},
	{"dump", FN_dump},
	{"e", FN_e},
	{"empty", FN_empty},
	{"enc", FN_enc},
	{"encode", FN_encode},
	{"end", FN_end},
	{"endsWith", FN_endsWith},
	{"equals", FN_equals},
	{"err", FN_err},
	{"eval", FN_eval},
	{"event", FN_event},
	{"exec", FN_exec},
	{"exit", FN_exit},
	{"extract", FN_extract},
	{"f", FN_f},
	{"flag", FN_flag},
	{"flush", FN_flush},
	{"fmt", FN_fmt},
	{"format", FN_format},
	{"gc", FN_gc},
	{"hashCode", FN_hashCode},
	{"hour", FN_hour},
	{"in", FN_in},
	{"indexOf", FN_indexOf},
	{"init", FN_init},
	{"initCapacity", FN_initCapacity},
	{"insert", FN_insert},
	{"it", FN_it},
	{"k", FN_k},
	{"key", FN_key},
	{"keys", FN_keys},
	{"lastIndexOf", FN_lastIndexOf},
	{"length", FN_length},
	{"listProperties", FN_listProperties},
	{"m", FN_m},
	{"main", FN_main},
	{"match", FN_match},
	{"method", FN_method},
	{"min", FN_min},
	{"mode", FN_mode},
	{"month", FN_month},
	{"msg", FN_msg},
	{"mtd", FN_mtd},
	{"n", FN_n},
	{"name", FN_name},
	{"new", FN_new},
	{"new:ARRAY", FN_new__ARRAY},
	{"new:LIST", FN_new__LIST},
	{"new:MAP", FN_new__MAP},
	{"new:TUPLE", FN_new__TUPLE},
	{"notNull", FN_notNull},
	{"null", FN_null},
	{"offset", FN_offset},
	{"open", FN_open},
	{"option", FN_option},
	{"out", FN_out},
	{"path", FN_path},
	{"pattern", FN_pattern},
	{"pooled", FN_pooled},
	{"pop", FN_pop},
	{"print", FN_print},
	{"println", FN_println},
	{"proceed", FN_proceed},
	{"property", FN_property},
	{"random", FN_random},
	{"randomSeed", FN_randomSeed},
	{"re", FN_re},
	{"readLine", FN_readLine},
	{"remove", FN_remove},
	{"replace", FN_replace},
	{"reverse", FN_reverse},
	{"s", FN_s},
	{"search", FN_search},
	{"sec", FN_sec},
	{"seed", FN_seed},
	{"send", FN_send},
	{"seq", FN_seq},
	{"shuffle", FN_shuffle},
	{"size", FN_size},
	{"sort", FN_sort},
	{"split", FN_split},
	{"start", FN_start},
	{"startsWith", FN_startsWith},
	{"status", FN_status},
	{"substring", FN_substring},
	{"swap", FN_swap},
	{"this", FN_this},
	{"time", FN_time},
	{"tmr", FN_tmr},
	{"to", FN_to},
	{"trace", FN_trace},
	{"trim", FN_trim},
	{"typeCheck", FN_typeCheck},
	{"u", FN_u},
	{"urn", FN_urn},
	{"v", FN_v},
	{"value", FN_value},
	{"vargs", FN_vargs},
	{"w", FN_w},
	{"write", FN_write},
	{"x", FN_x},
	{"xdata", FN_xdata},
	{"y", FN_y},
	{"year", FN_year},
	{"z", FN_z},
	{NULL}
};

static kloaddata_t ParamData0[] = {
	DATA_PARAM/*0*/, 0, 0, 0, 
	DATA_PARAM/*1*/, 0, 0, 1, T_This, FN_return,
	DATA_PARAM/*2*/, FLAG_Param_VARGs, 1, 1, TY_dynamic, FN_value, T_This, FN_return,
	DATA_PARAM/*3*/, 0, 0, 1, T_Class, FN_return,
	DATA_PARAM/*4*/, 0, 0, 1, TY_Int, FN_return,
	DATA_PARAM/*5*/, 0, 0, 1, TY_Boolean, FN_return,
	DATA_PARAM/*6*/, 0, 1, 1, T_TypeMap, FN_tmr, T_dyn, FN_return,
	DATA_PARAM/*7*/, 0, 1, 1, T_Class, FN_auto, TY_dynamic, FN_return,
	DATA_PARAM/*8*/, 0, 3, 1, T_Map, FN_data, T_KonohaSpace, FN_, TY_Boolean, FN_, TY_dynamic, FN_return,
	DATA_PARAM/*9*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_Tdynamic, FN_return,
	DATA_PARAM/*10*/, 0, 1, 0, TY_Int, FN_seed,
	DATA_PARAM/*11*/, 0, 1, 1, TY_Int, FN_n, TY_Int, FN_return,
	DATA_PARAM/*12*/, 0, 0, 1, T_Float, FN_return,
	DATA_PARAM/*13*/, 0, 6, 1, TY_Int, FN_year, TY_Int, FN_month, TY_Int, FN_day, TY_Int, FN_hour, TY_Int, FN_min, TY_Int, FN_sec, T_Date, FN_return,
	DATA_PARAM/*14*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_Date, FN_return,
	DATA_PARAM/*15*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_Path, FN_return,
	DATA_PARAM/*16*/, 0, 1, 1, TY_Int, FN_init, T_Bytes, FN_return,
	DATA_PARAM/*17*/, 0, 1, 1, TY_Int, FN_n, T_Pointer, FN_return,
	DATA_PARAM/*18*/, 0, 2, 1, T_Bytes, FN_buf, TY_StringDecoder, FN_c, TY_String, FN_return,
	DATA_PARAM/*19*/, 0, 2, 1, TY_String, FN_pattern, TY_String, FN_option, T_Regex, FN_return,
	DATA_PARAM/*20*/, 0, 3, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_Class, FN_, TY_dynamic, FN_return,
	DATA_PARAM/*21*/, 0, 1, 1, T_KonohaSpace, FN_, TY_Boolean, FN_return,
	DATA_PARAM/*22*/, 0, 1, 1, TY_String, FN_s, TY_Boolean, FN_return,
	DATA_PARAM/*23*/, FLAG_Param_VARGs, 1, 1, T_Object, FN_value, TY_String, FN_return,
	DATA_PARAM/*24*/, 0, 1, 1, TY_dynamic, FN_value, TY_String, FN_return,
	DATA_PARAM/*25*/, 0, 1, 1, TY_String, FN_s, TY_Int, FN_return,
	DATA_PARAM/*26*/, 0, 1, 1, T_Regex, FN_re, TY_Int, FN_return,
	DATA_PARAM/*27*/, 0, 1, 1, T_Regex, FN_re, TY_StringARRAY, FN_return,
	DATA_PARAM/*28*/, 0, 2, 1, T_Regex, FN_re, TY_String, FN_s, TY_String, FN_return,
	DATA_PARAM/*29*/, 0, 1, 1, T_Regex, FN_re, T_Map, FN_return,
	DATA_PARAM/*30*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_Converter, FN_return,
	DATA_PARAM/*31*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, TY_StringEncoder, FN_return,
	DATA_PARAM/*32*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, TY_StringDecoder, FN_return,
	DATA_PARAM/*33*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, TY_StringConverter, FN_return,
	DATA_PARAM/*34*/, 0, 1, 1, T_Converter, FN_enc, T_Bytes, FN_return,
	DATA_PARAM/*35*/, 0, 1, 1, TY_StringEncoder, FN_enc, T_Bytes, FN_return,
	DATA_PARAM/*36*/, 0, 1, 1, TY_StringDecoder, FN_c, TY_String, FN_return,
	DATA_PARAM/*37*/, 0, 1, 1, TY_StringConverter, FN_c, TY_String, FN_return,
	DATA_PARAM/*38*/, 0, 0, 1, TY_String, FN_return,
	DATA_PARAM/*39*/, 0, 0, 1, TY_StringITR, FN_return,
	DATA_PARAM/*40*/, 0, 2, 1, T_T1, FN_start, T_T1, FN_end, T_This, FN_return,
	DATA_PARAM/*41*/, 0, 1, 1, TY_Int, FN_initCapacity, T_This, FN_return,
	DATA_PARAM/*42*/, FLAG_Param_VARGs, 1, 1, TY_Int, FN_size, T_This, FN_return,
	DATA_PARAM/*43*/, FLAG_Param_VARGs, 1, 1, T_T1, FN_value, T_This, FN_return,
	DATA_PARAM/*44*/, 0, 2, 1, T_Object, FN_value, TY_Method, FN_mtd, T_This, FN_return,
	DATA_PARAM/*45*/, 0, 1, 1, TY_Int, FN_n, T_T1, FN_return,
	DATA_PARAM/*46*/, 0, 2, 1, TY_Int, FN_x, TY_Int, FN_y, T_T1, FN_return,
	DATA_PARAM/*47*/, 0, 3, 1, TY_Int, FN_x, TY_Int, FN_y, TY_Int, FN_z, T_T1, FN_return,
	DATA_PARAM/*48*/, 0, 4, 1, TY_Int, FN_x, TY_Int, FN_y, TY_Int, FN_z, TY_Int, FN_w, T_T1, FN_return,
	DATA_PARAM/*49*/, 0, 2, 1, TY_Int, FN_n, T_T1, FN_v, T_T1, FN_return,
	DATA_PARAM/*50*/, 0, 3, 1, TY_Int, FN_x, TY_Int, FN_y, T_T1, FN_v, T_T1, FN_return,
	DATA_PARAM/*51*/, 0, 4, 1, TY_Int, FN_x, TY_Int, FN_y, TY_Int, FN_z, T_T1, FN_v, T_T1, FN_return,
	DATA_PARAM/*52*/, 0, 5, 1, TY_Int, FN_x, TY_Int, FN_y, TY_Int, FN_z, TY_Int, FN_w, T_T1, FN_v, T_T1, FN_return,
	DATA_PARAM/*53*/, 0, 1, 1, T_T1, FN_v, T_T1, FN_return,
	DATA_PARAM/*54*/, FLAG_Param_VARGs, 1, 0, T_T1, FN_value,
	DATA_PARAM/*55*/, 0, 2, 0, TY_Int, FN_n, T_T1, FN_value,
	DATA_PARAM/*56*/, 0, 1, 0, TY_Int, FN_n,
	DATA_PARAM/*57*/, 0, 0, 1, T_T1, FN_return,
	DATA_PARAM/*58*/, 0, 1, 1, T_T1, FN_value, TY_Int, FN_return,
	DATA_PARAM/*59*/, 0, 1, 0, T_CmprT1, FN_cmr,
	DATA_PARAM/*60*/, 0, 2, 0, TY_Int, FN_m, TY_Int, FN_n,
	DATA_PARAM/*61*/, 0, 1, 1, T_FuncWhere, FN_f, T_This, FN_return,
	DATA_PARAM/*62*/, 0, 1, 1, T_FuncEach, FN_f, T_This, FN_return,
	DATA_PARAM/*63*/, 0, 1, 1, TY_Int, FN_init, T_This, FN_return,
	DATA_PARAM/*64*/, 0, 4, 1, TY_String, FN_path, T_Map, FN_, T_KonohaSpace, FN_, T_Class, FN_, T_Map, FN_return,
	DATA_PARAM/*65*/, 0, 2, 1, TY_String, FN_event, TY_String, FN_msg, T_Exception, FN_return,
	DATA_PARAM/*66*/, 0, 2, 1, TY_dynamic, FN_base, TY_Method, FN_method, T_This, FN_return,
	DATA_PARAM/*67*/, 0, 1, 1, TY_String, FN_msg, T_Assurance, FN_return,
	DATA_PARAM/*68*/, 0, 1, 1, T_Class, FN_c, TY_Boolean, FN_return,
	DATA_PARAM/*69*/, 0, 1, 1, TY_dynamic, FN_value, TY_Boolean, FN_return,
	DATA_PARAM/*70*/, 0, 1, 1, TY_Int, FN_value, TY_Boolean, FN_return,
	DATA_PARAM/*71*/, 0, 1, 1, T_Float, FN_value, TY_Boolean, FN_return,
	DATA_PARAM/*72*/, 0, 1, 1, TY_dynamic, FN_v, TY_Boolean, FN_return,
	DATA_PARAM/*73*/, 0, 1, 1, T_T1, FN_key, TY_Boolean, FN_return,
	DATA_PARAM/*74*/, 0, 1, 1, T_T1, FN_key, T_T2, FN_return,
	DATA_PARAM/*75*/, 0, 2, 0, T_T1, FN_key, T_T2, FN_value,
	DATA_PARAM/*76*/, 0, 1, 0, T_T1, FN_key,
	DATA_PARAM/*77*/, 0, 0, 1, T_T1ARRAY, FN_return,
	DATA_PARAM/*78*/, 0, 1, 1, TY_Int, FN_v, TY_Int, FN_return,
	DATA_PARAM/*79*/, 0, 1, 1, T_Float, FN_v, T_Float, FN_return,
	DATA_PARAM/*80*/, 0, 1, 1, T_Float, FN_n, T_Float, FN_return,
	DATA_PARAM/*81*/, 0, 1, 1, TY_String, FN_s, TY_String, FN_return,
	DATA_PARAM/*82*/, FLAG_Param_VARGs, 1, 1, TY_Int, FN_n, TY_Int, FN_return,
	DATA_PARAM/*83*/, 0, 2, 1, TY_Int, FN_n, TY_Int, FN_c, TY_Int, FN_return,
	DATA_PARAM/*84*/, 0, 1, 0, TY_Int, FN_c,
	DATA_PARAM/*85*/, 0, 1, 1, TY_Int, FN_n, TY_String, FN_return,
	DATA_PARAM/*86*/, 0, 2, 1, TY_Int, FN_s, TY_Int, FN_e, T_Bytes, FN_return,
	DATA_PARAM/*87*/, 0, 2, 1, TY_Int, FN_offset, TY_Int, FN_length, TY_String, FN_return,
	DATA_PARAM/*88*/, 0, 2, 1, TY_Int, FN_s, TY_Int, FN_e, TY_String, FN_return,
	DATA_PARAM/*89*/, 0, 2, 1, TY_Int, FN_s, TY_Int, FN_e, T_This, FN_return,
	DATA_PARAM/*90*/, 0, 3, 1, T_Path, FN_urn, TY_String, FN_mode, T_Map, FN_, T_InputStream, FN_return,
	DATA_PARAM/*91*/, 0, 3, 1, T_Path, FN_path, TY_String, FN_mode, T_Map, FN_, T_OutputStream, FN_return,
	DATA_PARAM/*92*/, 0, 3, 0, T_Bytes, FN_buf, TY_Int, FN_offset, TY_Int, FN_length,
	DATA_PARAM/*93*/, FLAG_Param_VARGs, 1, 0, T_Object, FN_value,
	DATA_PARAM/*94*/, FLAG_Param_VARGs, 1, 0, TY_dynamic, FN_value,
	DATA_PARAM/*95*/, FLAG_Param_VARGs, 1, 0, TY_String, FN_s,
	DATA_PARAM/*96*/, 0, 1, 1, TY_String, FN_fmt, TY_String, FN_return,
	DATA_PARAM/*97*/, 0, 3, 0, TY_String, FN_name, T_KonohaSpace, FN_, T_Map, FN_,
	DATA_PARAM/*98*/, 0, 2, 1, TY_String, FN_path, T_KonohaSpace, FN_, T_View, FN_return,
	DATA_PARAM/*99*/, 0, 0, 1, T_DataITR, FN_return,
	DATA_PARAM/*100*/, 0, 0, 1, T_InputStream, FN_return,
	DATA_PARAM/*101*/, 0, 0, 1, T_OutputStream, FN_return,
	DATA_PARAM/*102*/, 0, 1, 1, TY_String, FN_key, TY_dynamic, FN_return,
	DATA_PARAM/*103*/, 0, 2, 1, TY_String, FN_key, TY_dynamic, FN_value, TY_dynamic, FN_return,
	DATA_PARAM/*104*/, 0, 1, 1, TY_String, FN_key, TY_StringARRAY, FN_return,
	DATA_PARAM/*105*/, 0, 1, 0, TY_Int, FN_status,
	DATA_PARAM/*106*/, 0, 1, 1, TY_String, FN_event, TY_Boolean, FN_return,
	DATA_PARAM/*107*/, 0, 1, 1, TY_String, FN_cmd, TY_String, FN_return,
	DATA_PARAM/*108*/, 0, 4, 1, TY_String, FN_cmd, T_Script, FN_, T_KonohaSpace, FN_, T_Class, FN_, T_Tvar, FN_return,
	DATA_PARAM/*109*/, 0, 1, 1, TY_Boolean, FN_flag, TY_Boolean, FN_return,
	0
};
#define K_PARAM0_SIZE                   110

static kloaddata_t APIData0[] = {
	DATA_METHOD0, CLASS_Object, MN_new, FLAG_Method_Hidden, _DATA(Object_new), /*P=*/1,
	DATA_METHOD0, CLASS_Object, MN_new__MAP, FLAG_Method_Hidden, _DATA(Object_newMAP), /*P=*/2,
	DATA_METHOD0, CLASS_Object, MN_getClass, FLAG_Method_Const|FLAG_Method_FastCall, _DATA(Object_getClass), /*P=*/3,
	DATA_METHOD0, CLASS_Object, MN_hashCode, FLAG_Method_Const|FLAG_Method_FastCall, _DATA(Object_hashCode), /*P=*/4,
	DATA_METHOD0, CLASS_Object, MN_isNull, FLAG_Method_Const|FLAG_Method_Hidden|FLAG_Method_FastCall, _DATA(Object_isNull), /*P=*/5,
	DATA_METHOD0, CLASS_Object, MN_isNotNull, FLAG_Method_Const|FLAG_Method_Hidden|FLAG_Method_FastCall, _DATA(Object_isNotNull), /*P=*/5,
	DATA_METHOD0, CLASS_Object, MN_cast, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_cast), /*P=*/6,
	DATA_METHOD0, CLASS_Object, MN_to, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_to), /*P=*/7,
	DATA_METHOD0, CLASS_Object, MN_typeCheck, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_typeCheck), /*P=*/7,
	DATA_METHOD0, CLASS_Object, MN_opWITH, FLAG_Method_Hidden, _DATA(Object_opWITH), /*P=*/8,
	DATA_METHOD0, CLASS_Object, MN__empty, 0, _DATA(Object__empty), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__s, 0, _DATA(Object__s), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__k, 0, _DATA(Object__k), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__data, 0, _DATA(Object__data), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__dump, 0, _DATA(Object__dump), /*P=*/0,
	DATA_METHOD0, CLASS_Tdynamic, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(Tdynamic_opLINK), /*P=*/9,
	DATA_METHOD0, CLASS_Boolean, MN__s, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__k, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__data, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__dump, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__s, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__d, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__s, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__f, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__k, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__data, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__dump, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__k, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__data, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__dump, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_System, MN_setRandomSeed, FLAG_Method_Static|FLAG_Method_FastCall, _DATA(System_setRandomSeed), /*P=*/10,
	DATA_METHOD0, CLASS_Int, MN_random, FLAG_Method_Static|FLAG_Method_FastCall, _DATA(Int_random), /*P=*/11,
	DATA_METHOD0, CLASS_Float, MN_random, FLAG_Method_Static|FLAG_Method_FastCall, _DATA(Float_random), /*P=*/12,
	DATA_METHOD0, CLASS_Int, MN__c, 0, _DATA(Int__c), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__u, 0, _DATA(Int__u), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__f, 0, _DATA(Int__f), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__x, 0, _DATA(Int__x), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__bits, 0, _DATA(Int__bits), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__d, 0, _DATA(Float__d), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__bits, 0, _DATA(Float__bits), /*P=*/0,
	DATA_METHOD0, CLASS_Date, MN_new, 0, _DATA(Date_new), /*P=*/13,
	DATA_METHOD0, CLASS_Date, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(Date_opLINK), /*P=*/14,
	DATA_METHOD0, CLASS_Path, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(Path_opLINK), /*P=*/15,
	DATA_METHOD0, CLASS_Bytes, MN_new, 0, _DATA(Bytes_new), /*P=*/16,
	DATA_METHOD0, CLASS_Bytes, MN_new__ARRAY, 0, _DATA(Bytes_newARRAY), /*P=*/16,
	DATA_METHOD0, CLASS_Pointer, MN_opADD, 0, _DATA(Pointer_opADD), /*P=*/17,
	DATA_METHOD0, CLASS_String, MN_new, 0, _DATA(String_new), /*P=*/18,
	DATA_METHOD0, CLASS_Regex, MN_new, FLAG_Method_Const, _DATA(Regex_new), /*P=*/19,
	DATA_METHOD0, CLASS_String, MN_opLINK, FLAG_Method_Hidden, _DATA(String_opLINK), /*P=*/20,
	DATA_METHOD0, CLASS_String, MN_opEXISTS, FLAG_Method_Hidden, _DATA(String_opEXISTS), /*P=*/21,
	DATA_METHOD0, CLASS_String, MN_equals, FLAG_Method_Const, _DATA(String_equals), /*P=*/22,
	DATA_METHOD0, CLASS_String, MN_startsWith, FLAG_Method_Const, _DATA(String_startsWith), /*P=*/22,
	DATA_METHOD0, CLASS_String, MN_endsWith, FLAG_Method_Const, _DATA(String_endsWith), /*P=*/22,
	DATA_METHOD0, CLASS_String, MN_concat, FLAG_Method_Const, _DATA(String_concat), /*P=*/23,
	DATA_METHOD0, CLASS_String, MN_opADD, FLAG_Method_Const, _DATA(String_concat), /*P=*/24,
	DATA_METHOD0, CLASS_String, MN_indexOf, FLAG_Method_Const, _DATA(String_indexOf), /*P=*/25,
	DATA_METHOD0, CLASS_String, MN_lastIndexOf, FLAG_Method_Const, _DATA(String_lastIndexOf), /*P=*/25,
	DATA_METHOD0, CLASS_String, MN_search, FLAG_Method_Const, _DATA(String_search), /*P=*/26,
	DATA_METHOD0, CLASS_String, MN_match, FLAG_Method_Const, _DATA(String_match), /*P=*/27,
	DATA_METHOD0, CLASS_String, MN_replace, FLAG_Method_Const, _DATA(String_replace), /*P=*/28,
	DATA_METHOD0, CLASS_String, MN_split, FLAG_Method_Const, _DATA(String_split), /*P=*/27,
	DATA_METHOD0, CLASS_String, MN_extract, FLAG_Method_Const, _DATA(String_extract), /*P=*/29,
	DATA_METHOD0, CLASS_Converter, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(Converter_opLINK), /*P=*/30,
	DATA_METHOD0, CLASS_StringEncoder, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(StringEncoder_opLINK), /*P=*/31,
	DATA_METHOD0, CLASS_StringDecoder, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(StringDecoder_opLINK), /*P=*/32,
	DATA_METHOD0, CLASS_StringConverter, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(StringConverter_opLINK), /*P=*/33,
	DATA_METHOD0, CLASS_Bytes, MN_, FLAG_Method_Const, _DATA(Bytes_convert), /*P=*/34,
	DATA_METHOD0, CLASS_String, MN_encode, FLAG_Method_Const, _DATA(String_encode), /*P=*/35,
	DATA_METHOD0, CLASS_Bytes, MN_decode, FLAG_Method_Const, _DATA(Bytes_toString), /*P=*/36,
	DATA_METHOD0, CLASS_String, MN_, FLAG_Method_Const, _DATA(String_convert), /*P=*/37,
	DATA_METHOD0, CLASS_String, MN_convert, FLAG_Method_Const, _DATA(String_convert), /*P=*/37,
	DATA_METHOD0, CLASS_String, MN_trim, FLAG_Method_Const, _DATA(String_trim), /*P=*/38,
	DATA_METHOD0, CLASS_Regex, MN_opHAS, FLAG_Method_Const, _DATA(Regex_opHAS), /*P=*/22,
	DATA_METHOD0, CLASS_String, MN_opITR, 0, _DATA(String_Iterator), /*P=*/39,
	DATA_METHOD0, CLASS_Tuple, MN_new__TUPLE, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Tuple_newTUPLE), /*P=*/2,
	DATA_METHOD0, CLASS_Range, MN_new__LIST, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Range_newLIST), /*P=*/40,
	DATA_METHOD0, CLASS_Array, MN_new, 0, _DATA(Array_new), /*P=*/41,
	DATA_METHOD0, CLASS_Array, MN_new__ARRAY, FLAG_Method_Hidden, _DATA(Array_newARRAY), /*P=*/42,
	DATA_METHOD0, CLASS_Array, MN_new__LIST, FLAG_Method_Hidden, _DATA(Array_newLIST), /*P=*/43,
	DATA_METHOD0, CLASS_Iterator, MN_new, FLAG_Method_Hidden, _DATA(Iterator_new), /*P=*/44,
	DATA_METHOD0, CLASS_Array, MN_get, FLAG_Method_Immutable, _DATA(Array_get), /*P=*/45,
	DATA_METHOD0, CLASS_Array, MN_get2, FLAG_Method_Hidden|FLAG_Method_Immutable, _DATA(Array_get2), /*P=*/46,
	DATA_METHOD0, CLASS_Array, MN_get3, FLAG_Method_Hidden|FLAG_Method_Immutable, _DATA(Array_get3), /*P=*/47,
	DATA_METHOD0, CLASS_Array, MN_get4, FLAG_Method_Hidden|FLAG_Method_Immutable, _DATA(Array_get4), /*P=*/48,
	DATA_METHOD0, CLASS_Array, MN_set, 0, _DATA(Array_set), /*P=*/49,
	DATA_METHOD0, CLASS_Array, MN_set2, FLAG_Method_Hidden, _DATA(Array_set2), /*P=*/50,
	DATA_METHOD0, CLASS_Array, MN_set3, FLAG_Method_Hidden, _DATA(Array_set3), /*P=*/51,
	DATA_METHOD0, CLASS_Array, MN_set4, FLAG_Method_Hidden, _DATA(Array_set4), /*P=*/52,
	DATA_METHOD0, CLASS_Array, MN_setAll, 0, _DATA(Array_setAll), /*P=*/53,
	DATA_METHOD0, CLASS_Array, MN_add, 0, _DATA(Array_add), /*P=*/54,
	DATA_METHOD0, CLASS_Array, MN_send, 0, _DATA(Array_add), /*P=*/54,
	DATA_METHOD0, CLASS_Array, MN_insert, 0, _DATA(Array_insert), /*P=*/55,
	DATA_METHOD0, CLASS_Array, MN_clear, FLAG_Method_FastCall, _DATA(Array_clear), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN_remove, 0, _DATA(Array_remove), /*P=*/56,
	DATA_METHOD0, CLASS_Array, MN_pop, FLAG_Method_FastCall, _DATA(Array_pop), /*P=*/57,
	DATA_METHOD0, CLASS_Array, MN_indexOf, 0, _DATA(Array_indexOf), /*P=*/58,
	DATA_METHOD0, CLASS_Array, MN_lastIndexOf, 0, _DATA(Array_lastIndexOf), /*P=*/58,
	DATA_METHOD0, CLASS_Array, MN_sort, 0, _DATA(Array_sort), /*P=*/59,
	DATA_METHOD0, CLASS_Array, MN_swap, 0, _DATA(Array_swap), /*P=*/60,
	DATA_METHOD0, CLASS_Array, MN_shuffle, 0, _DATA(Array_shuffle), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN_reverse, 0, _DATA(Array_reverse), /*P=*/0,
	DATA_METHOD0, CLASS_Iterator, MN_opWHERE, FLAG_Method_Hidden, _DATA(Iterator_opWHERE), /*P=*/61,
	DATA_METHOD0, CLASS_Iterator, MN_opEACH, FLAG_Method_Hidden, _DATA(Iterator_opEACH), /*P=*/62,
	DATA_METHOD0, CLASS_Map, MN_new, 0, _DATA(Map_new), /*P=*/63,
	DATA_METHOD0, CLASS_Map, MN_new__MAP, FLAG_Method_Hidden, _DATA(Map_newMAP), /*P=*/43,
	DATA_METHOD0, CLASS_Map, MN_open, FLAG_Method_Static|FLAG_Method_Smart|FLAG_Method_Throwable, _DATA(Map_open), /*P=*/64,
	DATA_METHOD0, CLASS_Exception, MN_new, 0, _DATA(Exception_new), /*P=*/65,
	DATA_METHOD0, CLASS_Func, MN_new, 0, _DATA(Func_new), /*P=*/66,
	DATA_METHOD0, CLASS_Assurance, MN_new, FLAG_Method_Const, _DATA(Assurance_new), /*P=*/67,
	DATA_METHOD0, CLASS_Object, MN_opADDR, FLAG_Method_Const, _DATA(Object_opADDR), /*P=*/4,
	DATA_METHOD0, CLASS_Object, MN_opOF, FLAG_Method_Const, _DATA(Object_opOF), /*P=*/68,
	DATA_METHOD0, CLASS_Object, MN_opEQ, FLAG_Method_Const, _DATA(Object_opEQ), /*P=*/69,
	DATA_METHOD0, CLASS_Object, MN_opNOTEQ, FLAG_Method_Const, _DATA(Object_opNOTEQ), /*P=*/69,
	DATA_METHOD0, CLASS_Object, MN_opLT, FLAG_Method_Const, _DATA(Object_opLT), /*P=*/69,
	DATA_METHOD0, CLASS_Object, MN_opLTE, FLAG_Method_Const, _DATA(Object_opLTE), /*P=*/69,
	DATA_METHOD0, CLASS_Object, MN_opGT, FLAG_Method_Const, _DATA(Object_opGT), /*P=*/69,
	DATA_METHOD0, CLASS_Object, MN_opGTE, FLAG_Method_Const, _DATA(Object_opGTE), /*P=*/69,
	DATA_METHOD0, CLASS_Int, MN_opEQ, FLAG_Method_Const, _DATA(Int_opEQ), /*P=*/70,
	DATA_METHOD0, CLASS_Int, MN_opNOTEQ, FLAG_Method_Const, _DATA(Int_opNOTEQ), /*P=*/70,
	DATA_METHOD0, CLASS_Int, MN_opLT, FLAG_Method_Const, _DATA(Int_opLT), /*P=*/70,
	DATA_METHOD0, CLASS_Int, MN_opLTE, FLAG_Method_Const, _DATA(Int_opLTE), /*P=*/70,
	DATA_METHOD0, CLASS_Int, MN_opGT, FLAG_Method_Const, _DATA(Int_opGT), /*P=*/70,
	DATA_METHOD0, CLASS_Int, MN_opGTE, FLAG_Method_Const, _DATA(Int_opGTE), /*P=*/70,
	DATA_METHOD0, CLASS_Float, MN_opEQ, FLAG_Method_Const, _DATA(Float_opEQ), /*P=*/71,
	DATA_METHOD0, CLASS_Float, MN_opNOTEQ, FLAG_Method_Const, _DATA(Float_opNOTEQ), /*P=*/71,
	DATA_METHOD0, CLASS_Float, MN_opLT, FLAG_Method_Const, _DATA(Float_opLT), /*P=*/71,
	DATA_METHOD0, CLASS_Float, MN_opLTE, FLAG_Method_Const, _DATA(Float_opLTE), /*P=*/71,
	DATA_METHOD0, CLASS_Float, MN_opGT, FLAG_Method_Const, _DATA(Float_opGT), /*P=*/71,
	DATA_METHOD0, CLASS_Float, MN_opGTE, FLAG_Method_Const, _DATA(Float_opGTE), /*P=*/71,
	DATA_METHOD0, CLASS_String, MN_opHAS, FLAG_Method_Const, _DATA(String_opHAS), /*P=*/22,
	DATA_METHOD0, CLASS_Array, MN_opHAS, 0, _DATA(Array_opHAS), /*P=*/72,
	DATA_METHOD0, CLASS_Object, MN_opIS, FLAG_Method_Const, _DATA(Object_opIS), /*P=*/72,
	DATA_METHOD0, CLASS_Map, MN_opHAS, 0, _DATA(Map_opHAS), /*P=*/73,
	DATA_METHOD0, CLASS_Map, MN_get, 0, _DATA(Map_get), /*P=*/74,
	DATA_METHOD0, CLASS_Map, MN_set, 0, _DATA(Map_set), /*P=*/75,
	DATA_METHOD0, CLASS_Map, MN_remove, 0, _DATA(Map_remove), /*P=*/76,
	DATA_METHOD0, CLASS_Map, MN_keys, 0, _DATA(Map_keys), /*P=*/77,
	DATA_METHOD0, CLASS_Int, MN_opADD, FLAG_Method_Const, _DATA(Int_opADD), /*P=*/78,
	DATA_METHOD0, CLASS_Int, MN_opNEG, FLAG_Method_Const, _DATA(Int_opNEG), /*P=*/4,
	DATA_METHOD0, CLASS_Int, MN_opSUB, FLAG_Method_Const, _DATA(Int_opSUB), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opMUL, FLAG_Method_Const, _DATA(Int_opMUL), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opDIV, FLAG_Method_Const, _DATA(Int_opDIV), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opMOD, FLAG_Method_Const, _DATA(Int_opMOD), /*P=*/11,
	DATA_METHOD0, CLASS_Float, MN_opADD, FLAG_Method_Const, _DATA(Float_opADD), /*P=*/79,
	DATA_METHOD0, CLASS_Float, MN_opNEG, FLAG_Method_Const, _DATA(Float_opNEG), /*P=*/12,
	DATA_METHOD0, CLASS_Float, MN_opSUB, FLAG_Method_Const, _DATA(Float_opSUB), /*P=*/80,
	DATA_METHOD0, CLASS_Float, MN_opMUL, FLAG_Method_Const, _DATA(Float_opMUL), /*P=*/80,
	DATA_METHOD0, CLASS_Float, MN_opDIV, FLAG_Method_Const, _DATA(Float_opDIV), /*P=*/80,
	DATA_METHOD0, CLASS_String, MN_opSUB, FLAG_Method_Const, _DATA(String_opSUB), /*P=*/81,
	DATA_METHOD0, CLASS_Boolean, MN_opNOT, FLAG_Method_Const, _DATA(Boolean_opNOT), /*P=*/5,
	DATA_METHOD0, CLASS_Int, MN_opLAND, FLAG_Method_Const, _DATA(Int_opLAND), /*P=*/82,
	DATA_METHOD0, CLASS_Int, MN_opLOR, FLAG_Method_Const, _DATA(Int_opLOR), /*P=*/82,
	DATA_METHOD0, CLASS_Int, MN_opLXOR, FLAG_Method_Const, _DATA(Int_opLXOR), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opLNOT, FLAG_Method_Const, _DATA(Int_opLNOT), /*P=*/4,
	DATA_METHOD0, CLASS_Int, MN_opLSFT, FLAG_Method_Const, _DATA(Int_opLSFT), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_send, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Int_opLSFT), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opRSFT, FLAG_Method_Const, _DATA(Int_opRSFT), /*P=*/11,
	DATA_METHOD0, CLASS_Bytes, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/4,
	DATA_METHOD0, CLASS_Array, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/4,
	DATA_METHOD0, CLASS_Tuple, MN_getSize, 0, _DATA(Tuple_getSize), /*P=*/4,
	DATA_METHOD0, CLASS_String, MN_getSize, FLAG_Method_Const, _DATA(String_getSize), /*P=*/4,
	DATA_METHOD0, CLASS_Map, MN_getSize, 0, _DATA(Map_getSize), /*P=*/4,
	DATA_METHOD0, CLASS_Bytes, MN_get, 0, _DATA(Bytes_get), /*P=*/11,
	DATA_METHOD0, CLASS_Bytes, MN_set, 0, _DATA(Bytes_set), /*P=*/83,
	DATA_METHOD0, CLASS_Bytes, MN_setAll, 0, _DATA(Bytes_setAll), /*P=*/84,
	DATA_METHOD0, CLASS_String, MN_get, FLAG_Method_Const, _DATA(String_get), /*P=*/85,
	DATA_METHOD0, CLASS_Bytes, MN_opUNTIL, 0, _DATA(Bytes_opUNTIL), /*P=*/86,
	DATA_METHOD0, CLASS_Bytes, MN_opTO, 0, _DATA(Bytes_opTO), /*P=*/86,
	DATA_METHOD0, CLASS_String, MN_substring, FLAG_Method_Const, _DATA(String_substring), /*P=*/87,
	DATA_METHOD0, CLASS_String, MN_opUNTIL, FLAG_Method_Const, _DATA(String_opUNTIL), /*P=*/88,
	DATA_METHOD0, CLASS_String, MN_opTO, FLAG_Method_Const, _DATA(String_opTO), /*P=*/88,
	DATA_METHOD0, CLASS_Array, MN_opUNTIL, 0, _DATA(Array_opUNTIL), /*P=*/89,
	DATA_METHOD0, CLASS_Array, MN_opTO, 0, _DATA(Array_opTO), /*P=*/89,
	DATA_METHOD0, CLASS_Func, MN_, FLAG_Method_Hidden, _DATA(Func_invoke), /*P=*/0,
	DATA_METHOD0, CLASS_Thunk, MN_, FLAG_Method_Hidden, _DATA(Fmethod_returnConst), /*P=*/57,
	DATA_METHOD0, CLASS_Thunk, MN_eval, 0, _DATA(Thunk_eval), /*P=*/57,
	DATA_METHOD0, CLASS_Thunk, MN_getValue, 0, _DATA(Thunk_value), /*P=*/57,
	DATA_METHOD0, CLASS_InputStream, MN_new, FLAG_Method_Throwable, _DATA(InputStream_new), /*P=*/90,
	DATA_METHOD0, CLASS_InputStream, MN_close, 0, _DATA(InputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_InputStream, MN_readLine, FLAG_Method_Iterative, _DATA(InputStream_readLine), /*P=*/38,
	DATA_METHOD0, CLASS_InputStream, MN_opITR, 0, _DATA(InputStream_String__), /*P=*/39,
	DATA_METHOD0, CLASS_Path, MN_opITR, 0, _DATA(Path_String__), /*P=*/39,
	DATA_METHOD0, CLASS_OutputStream, MN_new, FLAG_Method_Throwable, _DATA(OutputStream_new), /*P=*/91,
	DATA_METHOD0, CLASS_OutputStream, MN_write, 0, _DATA(OutputStream_write), /*P=*/92,
	DATA_METHOD0, CLASS_OutputStream, MN_print, 0, _DATA(OutputStream_print), /*P=*/93,
	DATA_METHOD0, CLASS_OutputStream, MN_println, 0, _DATA(OutputStream_println), /*P=*/94,
	DATA_METHOD0, CLASS_OutputStream, MN_send, FLAG_Method_Hidden, _DATA(OutputStream_send), /*P=*/95,
	DATA_METHOD0, CLASS_OutputStream, MN_flush, 0, _DATA(OutputStream_flush), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_close, 0, _DATA(OutputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Int_format), /*P=*/96,
	DATA_METHOD0, CLASS_Float, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Float_format), /*P=*/96,
	DATA_METHOD0, CLASS_String, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(String_format), /*P=*/96,
	DATA_METHOD0, CLASS_View, MN_addView, FLAG_Method_Static, _DATA(View_addView), /*P=*/97,
	DATA_METHOD0, CLASS_View, MN_opLINK, FLAG_Method_Const|FLAG_Method_Static|FLAG_Method_Hidden, _DATA(View_opLINK), /*P=*/98,
	DATA_METHOD0, CLASS_View, MN_opITR, FLAG_Method_Hidden, _DATA(View_opITR), /*P=*/99,
	DATA_METHOD0, CLASS_System, MN_getIn, FLAG_Method_Static, _DATA(System_getIn), /*P=*/100,
	DATA_METHOD0, CLASS_System, MN_getOut, FLAG_Method_Static, _DATA(System_getOut), /*P=*/101,
	DATA_METHOD0, CLASS_System, MN_getErr, FLAG_Method_Static, _DATA(System_getErr), /*P=*/101,
	DATA_METHOD0, CLASS_System, MN_getProperty, FLAG_Method_Static, _DATA(System_getProperty), /*P=*/102,
	DATA_METHOD0, CLASS_System, MN_setProperty, FLAG_Method_Static, _DATA(System_setProperty), /*P=*/103,
	DATA_METHOD0, CLASS_System, MN_listProperties, FLAG_Method_Hidden, _DATA(System_listProperties), /*P=*/104,
	DATA_METHOD0, CLASS_System, MN_gc, FLAG_Method_Static, _DATA(System_gc), /*P=*/0,
	DATA_METHOD0, CLASS_System, MN_getTime, 0, _DATA(System_getTime), /*P=*/4,
	DATA_METHOD0, CLASS_System, MN_exit, FLAG_Method_Restricted, _DATA(System_exit), /*P=*/105,
	DATA_METHOD0, CLASS_Context, MN_getTrace, 0, _DATA(Context_getTrace), /*P=*/38,
	DATA_METHOD0, CLASS_Context, MN_getSeq, 0, _DATA(Context_getSeq), /*P=*/4,
	DATA_METHOD0, CLASS_Exception, MN_opOF, 0, _DATA(Exception_opOF), /*P=*/106,
	DATA_METHOD0, CLASS_System, MN_exec, FLAG_Method_Static|FLAG_Method_Restricted, _DATA(System_exec), /*P=*/107,
	DATA_METHOD0, CLASS_System, MN_eval, FLAG_Method_Restricted, _DATA(System_eval), /*P=*/108,
	DATA_METHOD0, CLASS_System, MN_readLine, 0, _DATA(System_readLine), /*P=*/107,
	DATA_METHOD0, CLASS_String, MN_isASCII, 0, _DATA(_String_isASCII), /*P=*/5,
	DATA_METHOD0, CLASS_String, MN_isPooled, 0, _DATA(_String_isPooled), /*P=*/5,
	DATA_METHOD0, CLASS_OutputStream, MN_isAutoFlush, 0, _DATA(_OutputStream_isAutoFlush), /*P=*/5,
	DATA_METHOD0, CLASS_OutputStream, MN_setAutoFlush, 0, _DATA(_OutputStream_setAutoFlush), /*P=*/109,
	DATA_METHOD0, CLASS_Context, MN_isDebug, 0, _DATA(_Context_isDebug), /*P=*/5,
	DATA_METHOD0, CLASS_Context, MN_setDebug, 0, _DATA(_Context_setDebug), /*P=*/109,
	DATA_TYPEMAP, CLASS_Boolean, CLASS_String, FLAG_TypeMap_Const, _DATA(Boolean_String),
	DATA_TYPEMAP, CLASS_Int, CLASS_String, FLAG_TypeMap_Const, _DATA(Int_String),
	DATA_TYPEMAP, CLASS_Float, CLASS_String, FLAG_TypeMap_Const, _DATA(Float_String),
	DATA_TYPEMAP, CLASS_Float, CLASS_Int, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(Float_Int),
	DATA_TYPEMAP, CLASS_Int, CLASS_Float, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(Int_Float),
	DATA_TYPEMAP, CLASS_Date, CLASS_String, FLAG_TypeMap_Const, _DATA(Date_String),
	DATA_TYPEMAP, CLASS_String, CLASS_Path, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(String_Path),
	DATA_TYPEMAP, CLASS_Path, CLASS_String, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(Path_String),
	DATA_TYPEMAP, CLASS_Path, CLASS_Boolean, 0, _DATA(Path_Boolean),
	DATA_TYPEMAP, CLASS_Path, CLASS_InputStream, 0, _DATA(Path_InputStream),
	DATA_TYPEMAP, CLASS_Bytes, CLASS_Pointer, 0, _DATA(Bytes_Pointer),
	DATA_TYPEMAP, CLASS_String, CLASS_Int, FLAG_TypeMap_Const, _DATA(String_Int),
	DATA_TYPEMAP, CLASS_String, CLASS_Float, FLAG_TypeMap_Const, _DATA(String_Float),
	DATA_TYPEMAP, CLASS_String, CLASS_Bytes, FLAG_TypeMap_Const, _DATA(String_Bytes),
	DATA_TYPEMAP, CLASS_Bytes, CLASS_InputStream, 0, _DATA(Bytes_InputStream),
	DATA_TYPEMAP, CLASS_String, CLASS_Regex, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(String_Regex),
	DATA_TYPEMAP, CLASS_Thunk, CLASS_Tvoid, 0, _DATA(Thunk_value),
	DATA_TYPEMAP, CLASS_InputStream, CLASS_StringITR, 0, _DATA(InputStream_String__),
	DATA_TYPEMAP, CLASS_Path, CLASS_StringITR, 0, _DATA(Path_String__),
	0
};
