K.importPackage("konoha.string");
K.importPackage("python");

System.p(System.importPyModule("ktest").retInt());
System.p(System.importPyModule("ktest").retFloat());
System.p(System.importPyModule("ktest").retString());
System.p(System.importPyModule("ktest").retTrue());
System.p(System.importPyModule("ktest").retFalse());
System.p(System.importPyModule("ktest").retByteArray());
System.p(System.importPyModule("ktest").retComp());
System.p(System.importPyModule("ktest").retTuple());
System.p(System.importPyModule("ktest").retList());
System.p(System.importPyModule("ktest").retDict());

